---
mongodb_major_version: "8.0"
mongodb_package_version: "7.0.24"

mongodb_port: 27017
mongodb_bind_ip: "0.0.0.0"

mongodb_db_path: "/var/lib/mongo"
mongodb_log_path: "/var/log/mongodb/mongod.log"

mongodb_service_name: mongod

mongodb_replica_set_name: rs0
